# Generated by Django 5.2.6 on 2025-09-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
